# Generated by Django 5.0.6 on 2024-12-18 22:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0001_initial'),
        ('matriculas', '0005_combo_matricula_combo'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='material',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='matriculas.combo'),
        ),
        migrations.AddField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='tipo',
            field=models.CharField(choices=[('apostila', 'Apostila'), ('exercicio', 'Exercício'), ('outro', 'Outro')], default='outro', max_length=20),
        ),
        migrations.AddField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='matriculas.curso'),
        ),
    ]
