# Generated by Django 5.0.6 on 2024-12-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alterou_senha',
            field=models.BooleanField(default=False),
        ),
    ]
