# Generated by Django 5.0.6 on 2024-12-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0003_curso_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='duracao_meses',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
