# Generated by Django 5.0.6 on 2024-12-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0005_combo_matricula_combo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cursos',
            field=models.ManyToManyField(blank=True, null=True, through='matriculas.Matricula', to='matriculas.curso'),
        ),
    ]
