# Generated by Django 5.0.6 on 2024-12-18 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0006_alter_user_cursos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matriculas.curso'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cursos',
            field=models.ManyToManyField(through='matriculas.Matricula', to='matriculas.curso'),
        ),
    ]
